set rtp+=.
set rtp+=deps/plenary.nvim
set rtp+=deps/telescope.nvim
set rtp+=deps/popup.nvim
set noswapfile
runtime plugin/plenary.vim
runtime plugin/telescope.vim
runtime plugin/noteflow.vim
runtime ftdetect/noteflow.vim
